default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

development:
  <<: *default
  host: localhost
  database: test_guru

test:
  <<: *default
  database: test_guru_test

production:
  <<: *default
  database: test_guru_production
